# PASSO 2 
server:
  port: 8080 # porta do localhost
  servlet:
    context-path: /bootcamp # path para rodar o sistema

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/postgres
    url: postgres://jkmpzylgzqcsmo:73840ed4ebf4f7b8c07850aa11461ffeb5519862a19d55d92369038b4c0dc8d9@ec2-3-226-134-153.compute-1.amazonaws.com:5432/d28f9aet9ienlv
    #username: postgres
    username: jkmpzylgzqcsmo
    #password: 123456
    password: 73840ed4ebf4f7b8c07850aa11461ffeb5519862a19d55d92369038b4c0dc8d9
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander